version: 2.1

jobs:
  build:
    # Primary container image
    docker:
       - image: circleci/ruby:2.5.8

    # Service container image
#        - image: circleci/postgres:9.4

    steps:
      - checkout
      # cache: bundler
      - run: bundle clean
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install
      - save_cache:
          paths:
            - ~/.bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
